### PR TITLE
Fix issue when pulling from cells with some types of formulas is them

### LINKED ISSUE #22: Problem reading cells with some types of formulas
#### Description:

Reading from some cells with formulas in them leads to a crash in the closed xml package when trying to access the value. By my quick investigation, it looks like accessing the `Value` property of the `IXLCell` means the cell value is re-computed making use of some mechanism in the closedXML repo, and that it fails to do so if the cell contains certain formulas.

A way around this is to instead fetch the `CashedValue`, or potentially just fallback to this, by first calling the `TryGetValue` and if that fails, fall back to the `CashedValue`.

#### Steps to reproduce:

Will produce testfile that illustrates the issue.

#### Expected behaviour:

For sheets with formulas to pull, giving back the value in the cell, could be pre-computed, or live computed.

#### Test file(s):

Will raise PR and provide there.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #22

As stated in the issue, there are some issues with reading values from some cells that contain some types of formulas.

The code in this PR fixes the issue by falling back to the cached value of the cell for when getting the Value out fails.
I went with raising a warning if this happens, and if closedXML believes the cell needs recalculation. For all cases I have tested so far, the cached value will be correct, but raised the warning to be safe.

Saying that, I was not aware that the adapter actually recomputed the sheet to get the values. Would have assumed that it just got whatever was in the cell, so might be safe to remove the warning.
Happy for any input on this from reviewers.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Excel_Toolkit/%2323-FixIssueReadingSheetsWithSomeTypesOfForumlas?csf=1&web=1&e=7dFRFj

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

File: Excel_Adapter/Convert/FromExcel/CellContents.cs [hunk 1]
```diff
@@ -45,16 +45,37 @@ public static CellContents FromExcel(this IXLCell xLCell)
...
+
+
         }
 
+        /*******************************************/
+
+        [Description("Gets the value of the cell, or cached value if the TryGetValue method fails. Raises a warning if the cached value is used, and ClosedXML beleives the cell needs to be recalculated.")]
+        [Input("xLCell", "IXLCell to get the (cached) value from.")]
+        [Input("value", "Value or cached value of the cell.")]
+        public static object CellValueOrCashedValue(this IXLCell xLCell)
```
Comment (FraserGreenroyd) [inline Excel_Adapter/Convert/FromExcel/CellContents.cs:65]:
```suggestion
        public static object CellValueOrCachedValue(this IXLCell xLCell) 
```

File: Excel_Adapter/Convert/FromExcel/CellContents.cs [hunk 2]
```diff
@@ -45,16 +45,37 @@ public static CellContents FromExcel(this IXLCell xLCell)
...
+        [Input("value", "Value or cached value of the cell.")]
+        public static object CellValueOrCashedValue(this IXLCell xLCell) 
+        {
+            object value;
+            if (!xLCell.TryGetValue(out value)) 
+            {
+                //If not able to just get the value, then get the cached value
+                //If cell is flagged as needing recalculation, raise warning.
+                if (xLCell.NeedsRecalculation)
+                    BH.Engine.Base.Compute.RecordWarning($"Cell {xLCell?.Address?.ToString() ?? "unknown"} is flagged as needing to be recalculated, but this is not able to be done. The cached value for this cell is returned, which for most cases is correct, but please ensure the validity of the value.");
```
Comment (FraserGreenroyd) [inline Excel_Adapter/Convert/FromExcel/CellContents.cs:73]:
```suggestion
                    BH.Engine.Base.Compute.RecordWarning($"Cell {xLCell?.Address?.ToString() ?? "unknown"} is flagged as needing to be recalculated, but this is not able to be done. The cached value for this cell is returned, which for most cases is correct, but please check the validity of the value.");
```

File: Excel_Adapter/Convert/FromExcel/CellContents.cs [hunk 3]
```diff
@@ -45,16 +45,37 @@ public static CellContents FromExcel(this IXLCell xLCell)
             return new CellContents()
             {
                 Comment = xLCell.HasComment ? xLCell.Comment.Text : "",
-                Value = xLCell.Value,
+                Value = xLCell.CellValueOrCashedValue(),
```
Comment (FraserGreenroyd) [inline Excel_Adapter/Convert/FromExcel/CellContents.cs:48]:
```suggestion
                Value = xLCell.CellValueOrCachedValue(),
```

File: Excel_Adapter/CRUD/Read/Read.cs [hunk 4]
```diff
@@ -126,7 +126,7 @@ private List<IBHoMObject> ReadExcel(XLWorkbook workbook, string worksheet, strin
                 foreach (IXLRangeColumn column in ixlRange.Columns())
                 {
                     if (valuesOnly)
-                        dataRow.Add(ixlWorksheet.Cell(row.RowNumber(), column.ColumnNumber()).GetValue<object>());
+                        dataRow.Add(ixlWorksheet.Cell(row.RowNumber(), column.ColumnNumber()).CellValueOrCashedValue());
```
Comment (FraserGreenroyd) [inline Excel_Adapter/CRUD/Read/Read.cs:129]:
```suggestion
                        dataRow.Add(ixlWorksheet.Cell(row.RowNumber(), column.ColumnNumber()).CellValueOrCachedValue());
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Review by FraserGreenroyd — APPROVED** [review]
Testing against today's alpha using the test script provided shows these two errors on the canvas:
image

image

After rebasing this PR and compiling this toolkit, the errors change to warnings:

image

Same for both pulls.

This did pull through values whereas the alpha did not, so this PR represents an improvement to the overall workflow. I'm happy for this to be merged and deployed for further testing via alphas.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
